include("../execute/main_original.jl")
include("../execute/main_IGA.jl")
include("../execute/main_quartile.jl")
include("../execute/main_polyapprox.jl")
# include("../execute/main_polyapprox_flexible.jl")
include("../execute/main_IGApolyapprox.jl")
include("../execute/main_socapprox.jl")
include("../execute/main_lpm.jl")
include("../execute/main_maxcount.jl")